### ISSUE TITLE
Site Social Preview: Add metadata and default image

### ISSUE THREAD

**Issue by briangershon** [briangershon/solana-clicker-game#15]
## Goal

When posting a link on a social media sites (Twitter, Facebook, LinkedIn) there should be a nice preview image and title.

Let's initially use:

- Title: "Solana Clicker is an open-source web-based Solana blockchain game for desktop web browsers."
- Description: "Solana Clicker is an open-source game being developed to learn and demonstrate techniques for integrating with Solana programs and Solana NFTs."
- Image: Game screenshot

## How to test

When you submit your PR, a site preview link will be generated and you can use that for testing.

I'd recommend testing using both [Twitter Validator](https://cards-dev.twitter.com/validator) and [the Facebook Sharing tools](https://developers.facebook.com/tools/debug/).

## More info

Background: https://www.kontentino.com/blog/social-media-meta-tags-a-complete-guide/

**Comment by Yash-Var** [comment]
Can i work on this?

**Comment by briangershon** [comment]
Hey @Yash-Var, that would be great, thank you! I'll add a bit more info to this ticket.

**Comment by Yash-Var** [comment]
@briangershon I know how to add meta tag but I can not find the file on which I have to add the these meta data on your code, 

So , can you guide me on which file I have to add meta data . It would be good for me to solve this issue.

**Comment by briangershon** [comment]
Hey @Yash-Var you can add to this Head section: https://github.com/briangershon/solana-clicker-game/blob/main/web-ui/pages/index.tsx#L91

**Comment by Yash-Var** [comment]
@briangershon I have made a PR can you review it....

**Comment by Yash-Var** [comment]
@briangershon check my PR and guide me ......
